language: node_js
node_js:
- '8'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
os:
- linux
- osx
script:
- npm test
- npm -g install babel-cli
- babel ./ -d /tmp/testbuild --minified --ignore 'node_modules/'
- BUILDLOC=`pwd`
- wget -O /tmp/release-2.2.0.tar.gz https://github.com/megastep/makeself/archive/release-2.2.0.tar.gz && cd /tmp/ && tar -xzf release-2.2.0.tar.gz && cd $BUILDLOC
- cp `which node` ./node
- npm install
- mv .git ../.git
- sed 's/\/config.json/\/..\/config.json/g' server.js >server.js2 && rm -f server.js && mv server.js2 server.js
- /tmp/makeself-release-2.2.0/makeself.sh `pwd` "/tmp/cast" "Cast 1.0" "./node server.js" >/dev/null 2>&1 
- chmod +x /tmp/cast && cd /tmp && tar -cvzf /tmp/cast-$TRAVIS_OS_NAME.tar.gz ./cast && cd $BUILDLOC
- mv ../.git .git
- git reset --hard
deploy:
  provider: releases
  api_key:
    secure: BCnPsm6SE7Nv9k/7fSCnztAGUA7jNVX3t/lWvRX1gtSbQkjKZXVmiRQXHKTZVyTaux3diiE5tGTzd0dp7PPsUDOgWdA0O3Goe37hCz6iOml67DCkvgE4AHVU72mL7iaczlxipS72XkAH0IKLv0+RIVhbe9Dc5gzozxTAmAscEbDbFk3s7F6f9WbJBL4Asd8BVWCt0kSvjbAp1M/xBIvWMxiLyCEdXMW3pNYAGXFE7rIYHK2/OTaerppNfJSCZWAyWniqJVbCshLjFw4szO+eEeqPwGW1AL5xTHD0aFVchNEm9bNzelDAjS4eOqwiPPrfC2Hd3wVEDMgoAO6w1kadk6D8gcEQdgp2HzCu/JzXXbz9MEXkcEwhrpgTRM50A2DFt5PwtPOPpitQUGDHhMYqebBHRZXc27RS4QTgNVm3e5IknvlHTCQ5AhR2O7y5uZurGnGoBxbySxb0MWpU+0NihM85hNy9dDTm7zWdrSS1vW0OibeIa3GQJczoJDteHh50Ds1QbtX64HfoIwQdDeSZ3u8sNRC137SrkVNueDbv/ECHe55ZG+SaMmAe0aiBMom43SLQ1Gi/xqyIBnNCRoT1vMmqtQWHTFIQcIRmc7Gj/vivH9GuAsBpLo2pMMBrr78L1ElZWhfYUIC3bvg02+ShFaYgphRkte8IwGdTVUDo4os=
  file: /tmp/cast-${TRAVIS_OS_NAME}.tar.gz
  overwrite: true
  on:
    repo: innovate-technologies/Cast
    tags: true
